### ISSUE TITLE
Automatic retrieval of RPM GPG keys

### ISSUE THREAD

**Issue by djjudas21** [andyshinn/puppet-atomic#7]
We discussed this briefly in a previous PR, and you said you weren't keen on having a dependency on `wget`. While the dependency is a bit of a pain, to me having locally copied and packaged GPG keys is not a great idea as then you have to repackage your module when the key changes.

Possible solutions:
* Install the `wget` package ourselves and use my code more-or-less as-is
* Depend on a third-party `wget` module to fetch the key so we can handle the key installation
* I could publish my RPM GPG key management stuff as its own module which your module could simply call upon to fetch and install the key. (There are currently Forge modules for handling RPM GPG keys but they only install them from local files and won't fetch them from a repo.) This module could actually call upon existing modules separately to fetch and install the key.

Probably other options too.

**Comment by treydock** [comment]
I just hit the issue of GPG key being out of date, as I'm using a forked version of this module.  I thought I'd mention one solution I can submit as PR is utilizing my custom type/provider to handle GPG keys (https://github.com/treydock/puppet-gpg_key/issues) combined with https://github.com/nanliu/puppet-archive to handle downloading the key.

**Comment by andyshinn** [comment]
I'm happy to merge and release a new version if a PR is opened. Additionally, if anyone is interested in taking over this module, I'd be happy to transfer ownership. I have not been doing any Puppet related configuration for years.

**Comment by djjudas21** [comment]
@andyshinn In principle I'm happy to help manage this module (or indeed take it over if you want to drop it completely). I assume the burden of maintenance is low.

@treydock As I mentioned earlier in the thread, I think there definitely is scope for modernising the way this module handles keys and your module seems as good as any other solution I can think of.

**Comment by treydock** [comment]
@djjudas21 Another approach which might be considered "lazy" is to just define the yumrepo's gpgkey as the URL to the GPG key instead of a `file://` path.  In my experience yum will download the key and accept it which eases the burden of having to manage the key via a module.  I don't yet know what happens when the key changes, but my guess is that yum will download it if it doesn't match.

I've also found some packages (ie ossec 2.7.1) using the 'old' key and new packages (ossec 2.8.0) using the new key.  So the `gpgkey` value needs to contain both (I think, about to test).

**Comment by djjudas21** [comment]
@treydock Well, I think that approach is fine too. Some of my other repos are configured in that way. It would certainly avoid having to release a new version of this module every time Atomic change their key (and they've done that twice since I started using their repo about 2-3 years ago).

**Comment by treydock** [comment]
@djjudas21 The gpgkey change and other changes (some I've had in my fork for ages) are in #8

**Comment by djjudas21** [comment]
:+1:

**Comment by djjudas21** [comment]
Any progress on this? @andyshinn I'm still happy to take over or collaborate on maintaining and doing module releases since I use this module in production :smile:

**Comment by andyshinn** [comment]
Unfortunately, I'm without a computer for a while. I've added @djjudas21 and @treydock as collaborators to this repository. Feel free to merge the PR and tag a release.

Are you guys also deploying the modules from the forge? If so, I'll need to transfer the forge ownership to one of you as well. Not sure if I can push a new release to it. Maybe given a tarball that is something I could do from my phone :smiling_imp:

**Comment by djjudas21** [comment]
Thanks. I am deploying from the forge. If you're able to upload a tarball then I'm happy to merge, build and send you the tarball by email or whatever takes your fancy. I don't think it's possible to transfer ownership of a forge account and it makes me somewhat nervous to publish under someone else's name.

**Comment by andyshinn** [comment]
If you make a release on GitHub, you can tag, add the tarball of the puppet
build, and I can download it and post to the forge.

**Comment by djjudas21** [comment]
I've prepared release 0.2.0 so this should be ready to publish on the Forge: https://github.com/andyshinn/puppet-atomic/archive/0.2.0.tar.gz

**Comment by andyshinn** [comment]
I pushed that tarball to the forge. Give it a try.

**Comment by djjudas21** [comment]
Sorry to take so long to test this... the new release works fine :) Thanks for your effort!
